# Generated by Django 4.0.5 on 2022-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=20)),
                ('Course_Fee', models.IntegerField()),
                ('About_Course', models.CharField(max_length=1000)),
                ('Duration', models.CharField(max_length=100)),
            ],
        ),
    ]
