# Generated by Django 4.0.5 on 2022-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0002_course_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_model',
            name='BG_Image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
