# Generated by Django 4.0.5 on 2022-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0003_course_model_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='BG_Image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
