# Generated by Django 4.1 on 2022-08-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_CCMS', '0004_alter_course_model_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='BG_Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='user_registration_model',
            name='User_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.CreateModel(
            name='Course_Joining_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Joining_Date', models.DateField(auto_now_add=True)),
                ('Course_Joining_Forgn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_CCMS.course_model')),
                ('User_Course_Joining_Forgn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
