# Generated by Django 4.1 on 2022-08-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0005_alter_course_model_bg_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Teacher_Course_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_CCMS.course_model')),
            ],
        ),
    ]
