# Generated by Django 4.1 on 2022-08-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0007_course_notes_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration_model',
            name='Course_Forgn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_CCMS.course_model'),
        ),
    ]
