# Generated by Django 4.1 on 2022-08-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0008_user_registration_model_course_forgn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration_model',
            name='Course_Forgn',
        ),
    ]
