# Generated by Django 4.1 on 2022-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0009_remove_user_registration_model_course_forgn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration_model',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
