# Generated by Django 4.1 on 2022-08-10 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_CCMS', '0010_user_registration_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_notes_model',
            name='User_Course_Note_Forgn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
