# Generated by Django 4.1 on 2022-08-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_CCMS', '0012_remove_course_notes_model_teacher_forgn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_notes_model',
            name='User_Course_Note_Forgn',
        ),
    ]
